#开发环境配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fzjk?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.fzjk.guanwang: debug
  file:
    path: log/fzjk-dev.log
