spring:
  thymeleaf:
    mode: HTML
    cache: false #关掉模板引擎的缓存
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fzjk?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

  messages:
    basename: i18n/login
    encoding: UTF-8

mybatis:
  type-aliases-package: com.fzjk.guanwang.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
