spring:
  thymeleaf:
    mode: HTML
    cache: false #关掉模板引擎的缓存
  profiles:
    active: dev  #指定使用的yml文件
  messages:
    basename: i18n/login
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 30MB
      location: F://upload/imgs/
      max-request-size: 30MB

server:
  tomcat:
    max-http-form-post-size: 30MB
    max-swallow-size: 30MB
